import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Image from 'next/image';
import Navbar from '@/components/navbar';
import Footer from '@/components/footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
<<<<<<< HEAD
        <Navbar />
=======
      <HeaderTop />
      <HeaderMain />
      <Navbar />
      <Hero />
        <Slide />
>>>>>>> ee69120b7702f415170cacb2b3157a9f02e7b0d5
        {children}
        <Footer />
        </body>
    </html>
  )
}
